src/Entity/Reclamation.php
<?php

namespace App\Entity;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\Validator\Constraints as Assert;
use App\Repository\ReclamationRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints\GreaterThan;
use Symfony\Component\Validator\Constraints\LessThan;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Serializer\SerilizerInterface;
use Doctrine\Common\Collections\ArrayCollection;

#[ORM\Entity(repositoryClass: ReclamationRepository::class)]
class Reclamation
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Groups("Reclamation")]
    private ?string $type = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    #[Groups("Reclamation")]
    #[Assert\GreaterThanOrEqual('today')]
   #[Assert\LessThanOrEqual('+2 days')]
    private ?\DateTimeInterface $date_r = null;

    #[ORM\Column(length: 255)]
    #[Groups("Reclamation")]
    #[Assert\NotBlank(message:"Description reclamation doit etre non vide")]
     #[Assert\Length(min:7,max:10000, minMessage:"Doit etre > 7.", maxMessage:"Doit etre <=10000")]
    private ?string $description = null;


    

    public function getId(): ?int
    {
        return $this->id;
    }



    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getDateR(): ?\DateTimeInterface
    {
        return $this->date_r;
    }

    public function setDateR(\DateTimeInterface $date_r): self
    {
        $this->date_r = $date_r;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }
    public function __toString()
    {
        return (string) $this->getType();
        $this->getDateR();
        $this->getDescription();
        
    }


    public function __construct()
    {
        $this->date_r = new \DateTime('now');
        $this->messages = new ArrayCollection();
    }

   
    
    /*public function getClientName(): ?string
    {
        return $this->id_client->getNomClient();
    }*/




#[ORM\OneToMany(mappedBy: 'id_rec', targetEntity: Message::class)]
private $messages;

#[ORM\ManyToOne(inversedBy: 'reclamations')]
#[ORM\JoinColumn(name: 'id_client_id', referencedColumnName: 'id_client')]
private ?Client $id_client_id = null;


public function getMessages()
{
    return $this->messages;
}

public function addMessage(Message $message)
{
    if (!$this->messages->contains($message)) {
        $this->messages[] = $message;
        $message->setIdRec($this);
    }

    return $this;
}

public function removeMessage(Message $message)
{
    if ($this->messages->contains($message)) {
        $this->messages->removeElement($message);
        if ($message->getIdRec() === $this) {
            $message->setIdRec(null);
        }
    }

    return $this;
}

public function getIdClient(): ?Client
{
    return $this->id_client_id;
}

public function setIdClient(?Client $id_client_id): self
{
    $this->id_client_id = $id_client_id;

    return $this;
}
public function getClientName(): ?string
{
    return $this->id_client_id ? $this->id_client_id->getNomClient() : null;
}

public function getIdClientId(): ?Client
{
    return $this->id_client_id;
}

public function setIdClientId(?Client $id_client_id): self
{
    $this->id_client_id = $id_client_id;

    return $this;
}

}

src/Form/ReclamationType.php
<?php

namespace App\Form;

use App\Entity\Reclamation;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Captcha\Bundle\CaptchaBundle\Validator\Constraints\ValidCaptcha;
use Gregwar\CaptchaBundle\Type\CaptchaType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;

class ReclamationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {   

        $options = array(
            'technique' => 'technique',
            'service' => 'service',
            'autre ' => 'autre',
        );
        $builder
        ->add('type', ChoiceType::class, array(
            'choices' => $options,
        ))
            ->add('date_r')
            ->add('description');
            //->add('id_client')
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Reclamation::class,
        ]);
    }
}

src/Controller/ReclamationController.php
<?php

namespace App\Controller;

use App\Entity\Reclamation;
use App\Form\Reclamation1Type;
use App\Repository\ReclamationRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/rec')]
class ReclamationController extends AbstractController
{
    #[Route('/aff', name: 'app_reclamation_index', methods: ['GET'])]
    public function index(ReclamationRepository $reclamationRepository): Response
    {
        return $this->render('reclamation/index.html.twig', [
            'reclamations' => $reclamationRepository->findAll(),
        ]);
    }



    #[Route('/home', name: 'app_reclamation_index1', methods: ['GET'])]
    public function index1(ReclamationRepository $reclamationRepository): Response
    {
        return $this->render('reclamation/new.html.twig');
    }

    #[Route('/addnewrec', name: 'app_reclamation_ne', methods: ['GET', 'POST'])]
    public function new(Request $request, ReclamationRepository $reclamationRepository): Response
    {
        $reclamation = new Reclamation();
        $form = $this->createForm(Reclamation1Type::class, $reclamation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $reclamationRepository->save($reclamation, true);

            return $this->redirectToRoute('app_reclamation_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('reclamation/_form.html.twig', [
            'reclamation' => $reclamation,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_reclamation_show', methods: ['GET'])]
    public function show(Reclamation $reclamation): Response
    {
        return $this->render('reclamation/show.html.twig', [
            'reclamation' => $reclamation,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_reclamation_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Reclamation $reclamation, ReclamationRepository $reclamationRepository): Response
    {
        $form = $this->createForm(Reclamation1Type::class, $reclamation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $reclamationRepository->save($reclamation, true);

            return $this->redirectToRoute('app_reclamation_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('reclamation/edit.html.twig', [
            'reclamation' => $reclamation,
            'form' => $form,
        ]);
    }

    #[Route('/delete/{id}', name: 'app_reclamation_delete', methods: ['POST'])]
    public function delete(Request $request, Reclamation $reclamation, ReclamationRepository $reclamationRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$reclamation->getId(), $request->request->get('_token'))) {
            $reclamationRepository->remove($reclamation, true);
        }

        return $this->redirectToRoute('app_reclamation_index', [], Response::HTTP_SEE_OTHER);
    }

    
}

templates/reclamation/_delete_form.html.twig
<form method="post" action="{{ path('app_reclamation_delete', {'id': reclamation.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ reclamation.id) }}">
    <button class="btn">Delete</button>
</form>

templates/reclamation/_form.html.twig
{% extends 'basefront.html.twig' %}
{% block title %}Reclamations{% endblock %}

{% block body %}
<div class="container-xxl py-5">
     <div class="container">
             <div class="row g-0">
                    <div class="bg-secondary p-5">
                        <p class="d-inline-block bg-dark text-primary py-1 px-4">reclamation</p>
                        <h1 class="text-uppercase mb-4">ajouter une reclamation</h1>
                        {{ form_start(form , {'attr': {'novalidate':'novalidate'}} ) }}
                        <form>
                            <div class="row g-3">
                                <div class="col-md-6">
                                    <form class="forms-sample">
                      <div class="form-group">
                        {{ form_row(form.type, {'label':'Type de réclamation' ,'attr':{'placeholder': 'type...', 'class':'form-control'}}) }}
                        </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                        {{ form_row(form.date_r, {'label':'Selectionner la date' ,'attr':{'placeholder': 'date_r...', 'class':'form-control'}}) }}
                        </div>
                                </div>
                                <div class="col-12">
                                    <div class="form-group">
                        {{ form_row(form.description, {'label':'Description' ,'attr':{'placeholder': 'description...', 'class':'form-control'}}) }}
                        </div>
                                </div>
                                <div class="col-12">
                                    <button class="btn btn-primary w-100 py-3" type="submit">Envoyer</button>
                                </div>
                            </div>
                             {{form_end(form)}}
                        </form>
                        <a href="{{ path('app_reclamation_index') }}">back to list</a>
                 </div>
            </div>
        </div>
</div>

            {% endblock %}
            

templates/reclamation/edit.html.twig
{% extends 'basefront.html.twig' %}


{% block header %}
{% endblock %}
{% block body %}
    <h1>Edit Reclamation</h1>

    {{ include('reclamation/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_reclamation_index') }}">back to list</a>

    {{ include('reclamation/_delete_form.html.twig') }}
{% endblock %}

templates/reclamation/index.html.twig
{% extends 'baseback.html.twig' %}
{% block title %}Reclamation{% endblock %}

{% block body %}
<div class="container-fluid pt-4 px-4">
                <div class="bg-secondary text-center rounded p-4">
                    <div class="d-flex align-items-center justify-content-between mb-4">
                        <h6 class="mb-0">les réclamations</h6>
                        <a href="">Show All</a>
                    </div>
                    <div class="table-responsive">
                        <table class="table text-start align-middle table-bordered table-hover mb-0">
                            <thead>
                                <tr class="text-white">
                                    
                                    <th scope="col">Id</th>
                                    <th scope="col">Type</th>
                                    <th scope="col">Date</th>
                                    <th scope="col">Description</th>
                                    <th scope="col">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                            {% for reclamation in reclamations %}
                                <tr>
                                     <td>{{ reclamation.id }}</td>
                                <td>{{ reclamation.type }}</td>
                                <td>{{ reclamation.dateR ? reclamation.dateR|date('Y-m-d') : '' }}</td>
                                <td>{{ reclamation.description }}</td>
                                <td>
                                    <a href="{{ path('app_reclamation_show', {'id': reclamation.id}) }}">show</a>
                                    <a href="{{ path('app_reclamation_edit', {'id': reclamation.id}) }}">edit</a>
                                </td>
                            </tr>
                                {% else %}
                            <tr>
                                <td colspan="5">no records found</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                    </div>
                </div>
            </div>
  
{% endblock %}

templates/reclamation/show.html.twig
{% extends 'baseback.html.twig' %}

{% block title %}Reclamation{% endblock %}

{% block body %}
    <h1>Reclamation</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ reclamation.id }}</td>
            </tr>
            <tr>
                <th>Type</th>
                <td>{{ reclamation.type }}</td>
            </tr>
            <tr>
                <th>Date_r</th>
                <td>{{ reclamation.dateR ? reclamation.dateR|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ reclamation.description }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_reclamation_index') }}">back to list</a>

    <a href="{{ path('app_reclamation_edit', {'id': reclamation.id}) }}">edit</a>

    {{ include('reclamation/_delete_form.html.twig') }}
{% endblock %}