src/Entity/Reservation.php
<?php

namespace App\Entity;

use App\Repository\ReservationRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ReservationRepository::class)]
class Reservation
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $nb_place = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date = null;

    #[ORM\Column(length: 255)]
    private ?string $point_de_depart = null;

    #[ORM\Column(length: 255)]
    private ?string $point_arrive = null;

    #[ORM\ManyToOne(inversedBy: 'reservations')]
    #[ORM\JoinColumn(name: 'id_client_id', referencedColumnName: 'id_client')]
    private ?Client $id_client_id = null;

    #[ORM\ManyToOne(inversedBy: 'reservations')]
    #[ORM\JoinColumn(name: 'id_conducteur_id', referencedColumnName: 'id_conducteur')]
    private ?Conducteur $id_conducteur_id = null;

    #[ORM\OneToOne(inversedBy: 'reservation', cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(nullable: false)]
    private ?Offre $id_offre = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNbPlace(): ?int
    {
        return $this->nb_place;
    }

    public function setNbPlace(int $nb_place): self
    {
        $this->nb_place = $nb_place;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getPointDeDepart(): ?string
    {
        return $this->point_de_depart;
    }

    public function setPointDeDepart(string $point_de_depart): self
    {
        $this->point_de_depart = $point_de_depart;

        return $this;
    }

    public function getPointArrive(): ?string
    {
        return $this->point_arrive;
    }

    public function setPointArrive(string $point_arrive): self
    {
        $this->point_arrive = $point_arrive;

        return $this;
    }

    public function getIdClient(): ?Client
    {
        return $this->id_client_id;
    }

    public function setIdClient(?Client $id_client): self
    {
        $this->id_client_id = $id_client;

        return $this;
    }

    public function getIdConducteur(): ?Conducteur
    {
        return $this->id_conducteur_id;
    }

    public function setIdConducteur(?Conducteur $id_conducteur): self
    {
        $this->id_conducteur_id = $id_conducteur;

        return $this;
    }

    public function getIdOffre(): ?Offre
    {
        return $this->id_offre;
    }

    public function setIdOffre(Offre $id_offre): self
    {
        $this->id_offre = $id_offre;

        return $this;
    }

    public function getIdClientId(): ?Client
    {
        return $this->id_client_id;
    }

    public function setIdClientId(?Client $id_client_id): self
    {
        $this->id_client_id = $id_client_id;

        return $this;
    }

    public function getIdConducteurId(): ?Conducteur
    {
        return $this->id_conducteur_id;
    }

    public function setIdConducteurId(?Conducteur $id_conducteur_id): self
    {
        $this->id_conducteur_id = $id_conducteur_id;

        return $this;
    }
}

src/Form/ReservationType.php
<?php

namespace App\Form;

use App\Entity\Conducteur;
use App\Entity\Offre;
use App\Entity\Client;



use App\Entity\Reservation;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;


class ReservationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nb_place')
            ->add('date')
            ->add('point_de_depart')
            ->add('point_arrive')
             ->add('id_client', EntityType::class, [
                'class' => Client::class,
                'choice_label' => 'id_client', // Remplacez "nom_complet" par le nom de l'attribut qui représente le nom complet du conducteur dans l'entité Conducteur
            ])
            ->add('id_conducteur', EntityType::class, [
                'class' => Conducteur::class,
                'choice_label' => 'id_conducteur', // Remplacez "nom_complet" par le nom de l'attribut qui représente le nom complet du conducteur dans l'entité Conducteur
            ])
             
            ->add('id_offre', EntityType::class, [
                'class' => Offre::class,
                'choice_label' => 'id', // Remplacez "nom_complet" par le nom de l'attribut qui représente le nom complet du conducteur dans l'entité Conducteur
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Reservation::class,
        ]);
    }
}

src/Controller/ReservationController.php
<?php

namespace App\Controller;

use App\Entity\Reservation;
use App\Entity\Client;
use App\Entity\Offre;
 use App\Service\CommentMailer;
use App\Form\ReservationType;
use App\Repository\ReservationRepository;
use App\Repository\OffreRepository;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

use Knp\Component\Pager\PaginatorInterface;

use Symfony\Component\Mime\Email;
use App\Service\MailerService;
use Symfony\Component\Mailer\MailerInterface;
use Knp\Bundle\PaginatorBundle\Pagination\SlidingPaginationInterface;
use Knp\Bundle\PaginatorBundle\Twig\Extension\PaginationExtension;

#[Route('/reservation')]
class ReservationController extends AbstractController
{
    #[Route('/', name: 'app_reservation1_index', methods: ['GET'])]
    public function index(ReservationRepository $reservationRepository, Request $request, PaginatorInterface $paginator): Response
    {
         
            $reservations = $reservationRepository->findAll();
            $reservations = $paginator->paginate(
                $reservations,
                $request->query->getInt('page', 1),
                1
            );
            return $this->render('reservation/index.html.twig', [
                'reservations' => $reservations,
    
            ]);
             
        
    }

    #[Route('/reservation', name: 'app_reservation_index', methods: ['GET'])]
    public function index2(ReservationRepository $reservationRepository, Request $request, PaginatorInterface $paginator): Response
    {
         
            $reservations = $reservationRepository->findAll();
            $reservations = $paginator->paginate(
                $reservations,
                $request->query->getInt('page', 1),
                1
            );
            return $this->render('reservation/index.html.twig', [
                'reservations' => $reservations,
    
            ]);
             
        
    }


    #[Route('/listReservation', name: 'app_reservation_index_Client', methods: ['GET'])]
    public function indexClient(ReservationRepository $reservationRepository): Response
    {
        return $this->render('reservation/indexClient.html.twig', [
            'reservations' => $reservationRepository->findAll(),
        ]);
    }

    #[Route('/listReservation/{id_client_id}', name: 'app_reservation_index_Clientid', methods: ['GET'])]
    public function indexClientid(ReservationRepository $reservationRepository, $id_client_id): Response
    {
        return $this->render('reservation/indexClient.html.twig', [
            'reservations' => $reservationRepository->findBy(['id_client_id' => $id_client_id]),
        ]);
    }

    #[Route('/new', name: 'app_reservation_new', methods: ['GET', 'POST'])]
    public function new(Request $request, ReservationRepository $reservationRepository ): Response
    {
        $reservation = new Reservation();
        $form = $this->createForm(ReservationType::class, $reservation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $reservationRepository->save($reservation, true);

             
            return $this->redirectToRoute('app_reservation_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('reservation/new.html.twig', [
            'reservation' => $reservation,
            'form' => $form,
        ]);
    }


    #[Route('front/new', name: 'app_reservation_new_front', methods: ['GET', 'POST'])]
    public function newfront(Request $request, ReservationRepository $reservationRepository): Response
    {
        $reservation = new Reservation();
        $form = $this->createForm(OffreType::class, $reservation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $reservationRepository->save($reservation, true);

            return $this->redirectToRoute('app_reservation_index_Client', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('reservation/newfront.html.twig', [
            'reservation' => $reservation,
            'form' => $form,
        ]);
    }


    #[Route('/reserverfront/new', name: 'app_reservation_new_reserver', methods: ['GET', 'POST'])]
    public function newfrontreserver(Request $request, ReservationRepository $reservationRepository,OffreRepository $offreRepository,MailerInterface $mailer): Response
    {
        $reservation = new Reservation();
        $offre = new Offre();
        $form = $this->createForm(ReservationType::class, $reservation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $reservationRepository->saveO($reservation,$mailer,  true);

            // $commentMailer->reserverOffre($reservation);
            // $commentMailer->reserverOffre($offre);
            return $this->redirectToRoute('app_reservation_index_Client', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('reservation/newfront.html.twig', [
            'reservation' => $reservation,
            'form' => $form,
        ]);
    }

     
   


    #[Route('/{id}', name: 'app_reservation_show', methods: ['GET'])]
    public function show(Reservation $reservation): Response
    {
        return $this->render('reservation/show.html.twig', [
            'reservation' => $reservation,
        ]);
    }

    #[Route('/{id}/showfront', name: 'app_reservation_showfront', methods: ['GET'])]
    public function showfront(Reservation $reservation): Response
    {
        return $this->render('reservation/showfront.html.twig', [
            'reservation' => $reservation,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_reservation_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Reservation $reservation, ReservationRepository $reservationRepository): Response
    {
        $form = $this->createForm(ReservationType::class, $reservation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $reservationRepository->save($reservation, true);

            return $this->redirectToRoute('app_reservation_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('reservation/edit.html.twig', [
            'reservation' => $reservation,
            'form' => $form,
        ]);
    }

    #[Route('editfront/{id}/', name: 'app_reservation_editfront', methods: ['GET', 'POST'])]
    public function editfront(Request $request, Reservation $reservation, ReservationRepository $reservationRepository): Response
    {
        $form = $this->createForm(ReservationType::class, $reservation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $reservationRepository->save($reservation, true);

            return $this->redirectToRoute('app_reservation_index_Client', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('reservation/editFront.html.twig', [
            'reservation' => $reservation,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_reservation_delete', methods: ['POST'])]
    public function delete(Request $request, Reservation $reservation,  ReservationRepository $reservationRepository ,MailerInterface $mailer): Response
    {
        if ($this->isCsrfTokenValid('delete'.$reservation->getId(), $request->request->get('_token'))) {
            $reservationRepository->remove($reservation,$mailer,  true);
        }

        // $commentMailer->sendEmailOffreremove($reservation );
        return $this->redirectToRoute('app_reservation_index_Client', [], Response::HTTP_SEE_OTHER);
    }
     
    #[Route('/stats', name: 'app_reservation_stats', methods: ['POST'])]
    public function statistiques(){
        return $this->render('offre/stats.html.twig');
    }
}

templates/reservation/_delete_form.html.twig
<form method="post" action="{{ path('app_reservation_delete', {'id': reservation.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ reservation.id) }}">
    <button class="btn">Delete</button>
</form>

templates/reservation/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/reservation/edit.html.twig
{% extends 'backbase.html.twig' %}

{% block title %}Edit Reservation{% endblock %}
{% block header %}

	<!-- Sidebar Start -->
	<div class="sidebar pe-4 pb-3">
		<nav class="navbar bg-secondary navbar-dark">
			<a href="dashboard" class="navbar-brand mx-4 mb-3">
				<img class="logo" src="{{ asset('img/logo.png') }}" alt="Logo" style="width: 150px;margin-top: -50px;
																				margin-bottom   : -67px; ">
			</a>
			<div class="d-flex align-items-center ms-4 mb-4">
				<div class="position-relative">
					<img class="rounded-circle" src="img/profile.png" alt="" style="width: 40px; height: 40px;">
					<div class="bg-success rounded-circle border border-2 border-white position-absolute end-0 bottom-0 p-1"></div>
				</div>
				<div class="ms-3">
					<h6 class="mb-0">Balkis Hmidi</h6>
					<span>Admin</span>
				</div>
			</div>
			<div class="navbar-nav w-100">
				<a href="dashboard" class="nav-item nav-link">
					<i class="fa fa-tachometer-alt me-2"></i>Dashboard</a>
				<div class="nav-item dropdown">
					<a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
						<i class="fa fa-user-edit me-2"></i>Utilisateurs</a>
					<div class="dropdown-menu bg-transparent border-0">
						<a href="#" class="dropdown-item">Clients</a>
						<a href="#" class="dropdown-item">Conducteur</a>
					</div>
				</div>
				<a href="{{ path('app_offre_index') }}" class="nav-item nav-link">
					<i class="fa fa-th me-2 active"></i>Offres</a>
				<a href="{{ path('app_reservation_index') }}" class="nav-item nav-link">
					<i class="fa fa-keyboard me-2"></i>Reservations</a>
				<a href="{{ path('app_commentaire') }}" class="nav-item nav-link  ">
					<i class="fa fa-table me-2"></i>Commentaire</a>
				<a href="{{ path('app_avis') }}" class="nav-item nav-link ">
					<i class="fa fa-star me-2"></i>Avis</a>
				<a href="#" class="nav-item nav-link">
					<i class="far fa-file-alt me-2"></i>Contrats</a>
				<a href="/aff" class="nav-item nav-link ">
					<i class="fa fa-keyboard me-2"></i>Réclamations</a>
				<a href="/message/aff" class="nav-item nav-link ">
					<i class="fa fa-table me-2"></i>Messages</a>

				<a href="{{ path('app_vehicule_contoller_index') }}" class="nav-item nav-link ">
					<i class="fa fa-table me-2"></i>Vehicules</a>

				<a href="{{ path('app_fournisseur_index') }}" class="nav-item nav-link ">
					<i class="fa fa-table me-2"></i>Fournisseur</a>
			</div>

		</nav>
	</div>
	<!-- Sidebar End -->


{% endblock %}

{% block body %}
    <h1>Edit Reservation</h1>

    {{ include('reservation/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_reservation_index') }}" target="_blank" class="btn btn-primary">back to list</a>

    {{ include('reservation/_delete_form.html.twig') }}
{% endblock %}

templates/reservation/editFront.html.twig
{% extends 'frontbase.html.twig' %}

{% block title %}Edit Reservation{% endblock %}

{% block body %}
    <h1>Edit Reservation</h1>

    {{ include('reservation/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_reservation_index_Client') }}" target="_blank" class="btn btn-primary">back to list</a>

    {{ include('reservation/_delete_form.html.twig') }}
{% endblock %}

templates/reservation/index.html.twig
{% extends 'backbase.html.twig' %}

{% block title %}La liste des reservations
{% endblock %}
{% block header %}

	<!-- Sidebar Start -->
	<div class="sidebar pe-4 pb-3">
		<nav class="navbar bg-secondary navbar-dark">
			<a href="dashboard" class="navbar-brand mx-4 mb-3">
				<img class="logo" src="{{ asset('img/logo.png') }}" alt="Logo" style="width: 150px;margin-top: -50px;
																				margin-bottom   : -67px; ">
			</a>
			<div class="d-flex align-items-center ms-4 mb-4">
				<div class="position-relative">
					<img class="rounded-circle" src="img/profile.png" alt="" style="width: 40px; height: 40px;">
					<div class="bg-success rounded-circle border border-2 border-white position-absolute end-0 bottom-0 p-1"></div>
				</div>
				<div class="ms-3">
					<h6 class="mb-0">Balkis Hmidi</h6>
					<span>Admin</span>
				</div>
			</div>
			<div class="navbar-nav w-100">
				<a href="dashboard" class="nav-item nav-link">
					<i class="fa fa-tachometer-alt me-2"></i>Dashboard</a>
				<div class="nav-item dropdown">
					<a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
						<i class="fa fa-user-edit me-2"></i>Utilisateurs</a>
					<div class="dropdown-menu bg-transparent border-0">
						<a href="#" class="dropdown-item">Clients</a>
						<a href="#" class="dropdown-item">Conducteur</a>
					</div>
				</div>
				<a href="{{ path('app_offre_index') }}" class="nav-item nav-link">
					<i class="fa fa-th me-2 active"></i>Offres</a>
				<a href="{{ path('app_reservation_index') }}" class="nav-item nav-link">
					<i class="fa fa-keyboard me-2"></i>Reservations</a>
				<a href="{{ path('app_commentaire') }}" class="nav-item nav-link  ">
					<i class="fa fa-table me-2"></i>Commentaire</a>
				<a href="{{ path('app_avis') }}" class="nav-item nav-link ">
					<i class="fa fa-star me-2"></i>Avis</a>
				<a href="#" class="nav-item nav-link">
					<i class="far fa-file-alt me-2"></i>Contrats</a>
				<a href="/aff" class="nav-item nav-link ">
					<i class="fa fa-keyboard me-2"></i>Réclamations</a>
				<a href="/message/aff" class="nav-item nav-link ">
					<i class="fa fa-table me-2"></i>Messages</a>

				<a href="{{ path('app_vehicule_contoller_index') }}" class="nav-item nav-link ">
					<i class="fa fa-table me-2"></i>Vehicules</a>

				<a href="{{ path('app_fournisseur_index') }}" class="nav-item nav-link ">
					<i class="fa fa-table me-2"></i>Fournisseur</a>
			</div>

		</nav>
	</div>
	<!-- Sidebar End -->


{% endblock %}
{% block body %}
	<h1>La liste des reservations</h1>

	<table class="table">
		<thead>
			<tr>
				<th>Id</th>
				<th>Nb_place</th>
				<th>Date</th>
				<th>Point_de_depart</th>
				<th>Point_arrive</th>
				<th>actions</th>
			</tr>
		</thead>
		<tbody>
			{% for reservation in reservations %}
				<tr>
					<td>{{ reservation.id }}</td>
					<td>{{ reservation.nbPlace }}</td>
					<td>{{ reservation.date ? reservation.date|date('Y-m-d') : '' }}</td>
					<td>{{ reservation.pointDeDepart }}</td>
					<td>{{ reservation.pointArrive }}</td>
					<td>
						<a href="{{ path('app_reservation_show', {'id': reservation.id}) }}" target="_blank" class="btn btn-primary">show</a>
					</td>
				</tr>
			{% else %}
				<tr>
					<td colspan="6">no records found</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
	{{ knp_pagination_render(reservations) }}

{% endblock %}

templates/reservation/indexClient.html.twig
{% extends 'frontbase.html.twig' %}

{% block title %}La liste des reservations{% endblock %}

{% block body %}
    <h1>La liste des reservations</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nb_place</th>
                <th>Date</th>
                <th>Point_de_depart</th>
                <th>Point_arrive</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for reservation in reservations %}
            <tr>
                <td>{{ reservation.id }}</td>
                <td>{{ reservation.nbPlace }}</td>
                <td>{{ reservation.date ? reservation.date|date('Y-m-d') : '' }}</td>
                <td>{{ reservation.pointDeDepart }}</td>
                <td>{{ reservation.pointArrive }}</td>
                <td>
                    <a href="{{ path('app_reservation_showfront', {'id': reservation.id}) }}" target="_blank" class="btn btn-primary">show</a>
             </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_offre_index_Client') }}" target="_blank" class="btn btn-primary">Create new</a>
{% endblock %}

templates/reservation/new.html.twig
{% extends 'frontbase.html.twig' %}

{% block title %}New Reservation{% endblock %}

{% block body %}
    <h1>Create new Reservation</h1>

    {{ include('reservation/_form.html.twig') }}

    <a href="{{ path('app_reservation_index') }}" target="_blank" class="btn btn-primary">back to list</a>
{% endblock %}

templates/reservation/newfront.html.twig
{% extends 'frontbase.html.twig' %}

{% block title %}Créer une nouvelle réservation{% endblock %}

{% block body %}
    <h1>Créer une nouvelle réservation</h1>

    {{ include('reservation/_form.html.twig') }}

    <a href="{{ path('app_offre_index_Client') }}">back to list</a>
{% endblock %}

templates/reservation/show.html.twig
{% extends 'backbase.html.twig' %}

{% block title %}Reservation{% endblock %}

{% block body %}
    <h1>Reservation</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ reservation.id }}</td>
            </tr>
            <tr>
                <th>Nb_place</th>
                <td>{{ reservation.nbPlace }}</td>
            </tr>
            <tr>
                <th>Date</th>
                <td>{{ reservation.date ? reservation.date|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Point_de_depart</th>
                <td>{{ reservation.pointDeDepart }}</td>
            </tr>
            <tr>
                <th>Point_arrive</th>
                <td>{{ reservation.pointArrive }}</td>
            </tr>
        </tbody>
    </table>

        <a href="{{ path('app_reservation_index') }}" target="_blank" class="btn btn-primary">back to list</a>


    {{ include('reservation/_delete_form.html.twig') }}
{% endblock %}

templates/reservation/showfront.html.twig
{% extends 'frontbase.html.twig' %}

{% block title %}Reservation{% endblock %}

{% block body %}
    <h1>Reservation</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ reservation.id }}</td>
            </tr>
            <tr>
                <th>Nb_place</th>
                <td>{{ reservation.nbPlace }}</td>
            </tr>
            <tr>
                <th>Date</th>
                <td>{{ reservation.date ? reservation.date|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Point_de_depart</th>
                <td>{{ reservation.pointDeDepart }}</td>
            </tr>
            <tr>
                <th>Point_arrive</th>
                <td>{{ reservation.pointArrive }}</td>
            </tr>
        </tbody>
    </table>

 <a href="{{ path('app_reservation_index_Client') }}">back to list</a>

    <a href="{{ path('app_reservation_editfront', {'id': reservation.id}) }}">edit</a>

    {{ include('reservation/_delete_form.html.twig') }}
{% endblock %}