src/Entity/Message.php
<?php

namespace App\Entity;
use Symfony\Component\Validator\Constraints as Assert;
use App\Repository\MessageRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use DateTimeInterface;
use Symfony\Component\Validator\Constraints\GreaterThan;
use Symfony\Component\Validator\Constraints\LessThan;


#[ORM\Entity(repositoryClass: MessageRepository::class)]
class Message
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;


    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message:"Contenu du message doit etre non vide")]
     #[Assert\Length(min:7,max:10000, minMessage:"Doit etre > 7.", maxMessage:"Doit etre <=10000")]
    private ?string $contenu = null;

    #[ORM\Column(type: Types::DATETIME_IMMUTABLE)]
private ?DateTimeInterface $date_message = null;

    #[ORM\ManyToOne(inversedBy: 'messages')]
    private ?Reclamation $id_rec = null;

    #[ORM\ManyToOne(inversedBy: 'messages')]
    #[ORM\JoinColumn(name: 'id_admin_id', referencedColumnName: 'id_admin')]
    #[Assert\NotBlank(message:"Admin doit etre selectionné")]
    private ?Admin $id_admin_id = null;

    

    public function getId(): ?int
    {
        return $this->id;
    }

   
    public function getContenu(): ?string
    {
        return $this->contenu;
    }

    public function setContenu(string $contenu): self
    {
        $this->contenu = $contenu;

        return $this;
    }

    public function getDateMessage(): ?DateTimeInterface
{
    return $this->date_message;
}

public function setDateMessage(DateTimeInterface $date_message): self
{
    $this->date_message = $date_message;

    return $this;
}

    

    public function getIdRec(): ?Reclamation
    {
        return $this->id_rec;
    }

    public function setIdRec(?Reclamation $id_rec): self
    {
        $this->id_rec = $id_rec;

        return $this;
    }
    public function __toString()
    {
        return (string) $this->getContenu();
        $this->getDateMessage();
        $this->getIdRec();
        
    }

    public function getIdAdmin(): ?Admin
    {
        return $this->id_admin_id;
    }

    public function setIdAdmin(?Admin $id_admin): self
    {
        $this->id_admin_id = $id_admin;

        return $this;
    }
    public function __construct()
{
    $this->date_message = new \DateTimeImmutable();

}


    /*public function getAdminName(): ?string
    {
        return $this->id_admin_id->getId();
    }*/
    public function getAdminName(): ?string
{
    return $this->id_admin_id->getEmailAd();
}
    public function getRec(): ?string
    {
        return $this->id_rec->getId();
    }
    

    /*{% if reclamation.messages|length > 0 %}
                {% set last_message = reclamation.messages|sort((a, b) => b.DateMessage<=> a.DateMessage)|first %}
                <button class="btn btn-success" onclick="window.location.href='{{ path('app_message_showpourclient', {'id': last_message.id}) }}'">Afficher la réponse</button>
            {% else %}
                Pas encore de réponse
            {% endif %}*/

            
            /*{% if reclamation.messages|length > 0 %}
                {% for message in reclamation.messages|sort((a, b) => a.DateMessage<=>b.DateMessage) %}
                    <button class="btn btn-success" onclick="window.location.href='{{ path('app_message_showpourclient', {'id': message.id}) }}'">{{ message.DateMessage|date('d/m/Y H:i:s') }} - Afficher la réponse</button><br>
                {% endfor %}
            {% else %}
                Pas encore de réponse
            {% endif %}*/

            public function getIdAdminId(): ?Admin
            {
                return $this->id_admin_id;
            }

            public function setIdAdminId(?Admin $id_admin_id): self
            {
                $this->id_admin_id = $id_admin_id;

                return $this;
            }
        
}

src/Form/MessageType.php
<?php

namespace App\Form;

use App\Entity\Message;
use App\Entity\Reclamation;
use App\Entity\Admin;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Validator\Constraints as Assert;



class MessageType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('contenu')
            ->add('date_message', DateTimeType::class, [
                'label' => 'Sélectionner la date',
                'widget' => 'single_text',
                'html5' => false,
                'format' => 'yyyy/MM/dd HH:mm',
                'input' => 'datetime_immutable',
            ])
            
            ->add('id_admin', EntityType::class, [
                'class' => Admin::class,
                'choice_label' => 'emailAd',
                'label' => 'Admin',
                'attr' => [
                    'class' => 'form-control'
                ]
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Message::class,
        ]);
    }
}

src/Controller/MessageController.php
<?php

namespace App\Controller;

use App\Entity\Message;
use App\Entity\Reclamation;
use App\Form\MessageType;
use App\Repository\MessageRepository;
use App\Repository\ReclamationRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/message')]
class MessageController extends AbstractController
{
    #[Route('/aff', name: 'app_message_index', methods: ['GET'])]
    public function index(MessageRepository $messageRepository): Response
    {
        return $this->render('message/index.html.twig', [
            'messages' => $messageRepository->findAll(),
        ]);
    }

    #[Route('/new/{id}', name: 'app_message_new', methods: ['GET', 'POST'])]
public function new(Request $request, MessageRepository $messageRepository, Reclamation $reclamation): Response
{
    $message = new Message();
    $message->setIdRec($reclamation);
    $form = $this->createForm(MessageType::class, $message);
    $form->handleRequest($request);

    if ($form->isSubmitted() && $form->isValid()) {
        $messageRepository->save($message, true);

        return $this->redirectToRoute('app_message_index', [], Response::HTTP_SEE_OTHER);
    }

    return $this->renderForm('message/new.html.twig', [
        'message' => $message,
        'form' => $form,
    ]);
}


    #[Route('/show/{id}', name: 'app_message_show', methods: ['GET'])]
    public function show(Message $message): Response
    {
        return $this->render('message/show.html.twig', [
            'message' => $message,
        ]);
    }

    #[Route('/{id}', name: 'app_message_showpourclient', methods: ['GET'])]
    public function showpourclient(Message $message): Response
    {
        return $this->render('message/showpourclient.html.twig', [
            'message' => $message,
        ]);
    }

  

    #[Route('/{id}/edit', name: 'app_message_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Message $message, MessageRepository $messageRepository): Response
    {
        $form = $this->createForm(MessageType::class, $message);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $messageRepository->save($message, true);

            return $this->redirectToRoute('app_message_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('message/edit.html.twig', [
            'message' => $message,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_message_delete', methods: ['POST'])]
    public function delete(Request $request, Message $message, MessageRepository $messageRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$message->getId(), $request->request->get('_token'))) {
            $messageRepository->remove($message, true);
        }

        return $this->redirectToRoute('app_message_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/message/_delete_form.html.twig
<form method="post" action="{{ path('app_message_delete', {'id': message.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ message.id) }}">
    <button class="btn">Delete</button>
</form>

templates/message/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary w-50 py-2">{{ button_label|default('Envoyer') }}</button>
    <a href="{{ path('app_rec_index') }}">back to list</a>
{{ form_end(form) }}

templates/message/edit.html.twig
{% extends 'backbase.html.twig' %}

{% block header %}
{% endblock %}
{% block sidebar %}
{% endblock %}
{% block body %}

    {{ include('message/new.html.twig', {'button_label': 'Update'}) }}

{% endblock %}
{% block footer %}
{% endblock %}

templates/message/index.html.twig
{% extends 'backbase.html.twig' %}
{% block title %}Message{% endblock %}
{% block header %}
       
        <!-- Sidebar Start -->
        <div class="sidebar pe-4 pb-3">
            <nav class="navbar bg-secondary navbar-dark">
                <a href="dashboard" class="navbar-brand mx-4 mb-3">
              <img class="logo" src="{{ asset('img/logo.png') }}" alt="Logo" style="width: 150px;margin-top: -50px;    
margin-bottom   : -67px; ">
                </a>
                <div class="d-flex align-items-center ms-4 mb-4">
                    <div class="position-relative">
                        <img class="rounded-circle" src="/img/profile.png" alt="" style="width: 40px; height: 40px;">
                        <div class="bg-success rounded-circle border border-2 border-white position-absolute end-0 bottom-0 p-1"></div>
                    </div>
                    <div class="ms-3">
                        <h6 class="mb-0">Balkis Hmidi</h6>
                        <span>Admin</span>
                    </div>
                </div>
                <div class="navbar-nav w-100">
                    <a href="dashboard" class="nav-item nav-link"><i class="fa fa-tachometer-alt me-2"></i>Dashboard</a>
                    <div class="nav-item dropdown">
                         <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown"><i class="fa fa-user-edit me-2"></i>Utilisateurs</a>
                        <div class="dropdown-menu bg-transparent border-0">
                            <a href="#" class="dropdown-item">Clients</a>
                            <a href="#" class="dropdown-item">Conducteur</a>
                        </div>
                    </div>
                    <a href="#" class="nav-item nav-link"><i class="fa fa-th me-2"></i>Offres</a>
                    <a href="#" class="nav-item nav-link"><i class="fa fa-keyboard me-2"></i>Reservations</a>
                    <a  href="{{ path('app_commentaire') }}" class="nav-item nav-link "><i class="fa fa-table me-2"></i>Commentaire</a>
                    <a href="{{ path('app_avis') }}" class="nav-item nav-link "><i class="fa fa-star me-2"></i>Avis</a>

{% block header %}
       
        <!-- Sidebar Start -->
        <div class="sidebar pe-4 pb-3">
            <nav class="navbar bg-secondary navbar-dark">
                <a href="dashboard" class="navbar-brand mx-4 mb-3">
              <img class="logo" src="{{ asset('img/logo.png') }}" alt="Logo" style="width: 150px;margin-top: -50px;    
margin-bottom   : -67px; ">
                </a>
                <div class="d-flex align-items-center ms-4 mb-4">
                    <div class="position-relative">
                        <img class="rounded-circle" src="img/profile.png" alt="" style="width: 40px; height: 40px;">
                        <div class="bg-success rounded-circle border border-2 border-white position-absolute end-0 bottom-0 p-1"></div>
                    </div>
                    <div class="ms-3">
                        <h6 class="mb-0">Balkis Hmidi</h6>
                        <span>Admin</span>
                    </div>
                </div>
                <div class="navbar-nav w-100">
                    <a href="dashboard" class="nav-item nav-link"><i class="fa fa-tachometer-alt me-2"></i>Dashboard</a>
                    <div class="nav-item dropdown">
                         <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown"><i class="fa fa-user-edit me-2"></i>Utilisateurs</a>
                        <div class="dropdown-menu bg-transparent border-0">
                            <a href="#" class="dropdown-item">Clients</a>
                            <a href="#" class="dropdown-item">Conducteur</a>
                        </div>
                    </div>
                    <a href="#" class="nav-item nav-link"><i class="fa fa-th me-2"></i>Offres</a>
                    <a href="#" class="nav-item nav-link"><i class="fa fa-keyboard me-2"></i>Reservations</a>
                    <a  href="{{ path('app_commentaire') }}" class="nav-item nav-link active "><i class="fa fa-table me-2"></i>Commentaire</a>
                    <a href="{{ path('app_avis') }}" class="nav-item nav-link "><i class="fa fa-star me-2"></i>Avis</a>
                       <a href="/contratf/back"  class="nav-item nav-link" ><i class="far fa-file-alt me-2"></i>Contrats</a>
                    <a href="/aff" class="nav-item nav-link " ><i class="fa fa-keyboard me-2"></i>Réclamations</a>
                <a href="/message/aff" class="nav-item nav-link "><i class="fa fa-table me-2"></i>Messages</a>
                </div>
               
            </nav>
        </div>
        <!-- Sidebar End -->



{% endblock %}                    <a href="/aff" class="nav-item nav-link " ><i class="fa fa-keyboard me-2"></i>Réclamations</a>
                <a href="/message/aff" class="nav-item nav-link active"><i class="fa fa-table me-2"></i>Messages</a>
                </div>
               
            </nav>
        </div>
        <!-- Sidebar End -->



{% endblock %}
{% block body %}
<style>
        h1 {
            color: black;
            font-size: 24px;
        }
    </style>
<div class="container" style="background-color: white; height: 900px;">
    <h1>Messages envoyés</h1>

    <table class="table table-bordered table-striped table-hover" style="width: 80%;">
        <thead>
            <tr>
                <th>Id</th>
                <th>Contenu</th>
                <th>Date_message</th>             
                <th>Admin</th>
                <th>Id de Reclamation</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
        {% for message in messages %}
            <tr>
                <td>{{ message.id }}</td>
                <td>{{ message.contenu }}</td>
                <td>{{ message.dateMessage ? message.dateMessage|date('Y-m-d H:i:s') : '' }}</td>
                
                <td>{{ message.getAdminName() }}</td>
                <td>{{ message.getRec() }}</td>
                <td>
                    <a href="{{ path('app_message_show', {'id': message.id}) }}">show</a>
                    <a href="{{ path('app_message_edit', {'id': message.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <a href="{{ path('app_rec_index') }}">voir les réclamations</a>
    </div>
{% endblock %}

templates/message/new.html.twig
{% extends 'backbase.html.twig' %}
{% block title %}Message{% endblock %}
{% block header %}
       
        <!-- Sidebar Start -->
        <div class="sidebar pe-4 pb-3">
            <nav class="navbar bg-secondary navbar-dark">
                <a href="dashboard" class="navbar-brand mx-4 mb-3">
              <img class="logo" src="{{ asset('img/logo.png') }}" alt="Logo" style="width: 150px;margin-top: -50px;    
margin-bottom   : -67px; ">
                </a>
                <div class="d-flex align-items-center ms-4 mb-4">
                    <div class="position-relative">
                        <img class="rounded-circle" src="/img/profile.png" alt="" style="width: 40px; height: 40px;">
                        <div class="bg-success rounded-circle border border-2 border-white position-absolute end-0 bottom-0 p-1"></div>
                    </div>
                    <div class="ms-3">
                        <h6 class="mb-0">Balkis Hmidi</h6>
                        <span>Admin</span>
                    </div>
                </div>
                <div class="navbar-nav w-100">
                    <a href="dashboard" class="nav-item nav-link"><i class="fa fa-tachometer-alt me-2"></i>Dashboard</a>
                    <div class="nav-item dropdown">
                         <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown"><i class="fa fa-user-edit me-2"></i>Utilisateurs</a>
                        <div class="dropdown-menu bg-transparent border-0">
                            <a href="#" class="dropdown-item">Clients</a>
                            <a href="#" class="dropdown-item">Conducteur</a>
                        </div>
                    </div>
                    <a href="#" class="nav-item nav-link"><i class="fa fa-th me-2"></i>Offres</a>
                    <a href="#" class="nav-item nav-link"><i class="fa fa-keyboard me-2"></i>Reservations</a>
                    <a  href="{{ path('app_commentaire') }}" class="nav-item nav-link "><i class="fa fa-table me-2"></i>Commentaire</a>
                    <a href="{{ path('app_avis') }}" class="nav-item nav-link "><i class="fa fa-star me-2"></i>Avis</a>

{% block header %}
       
        <!-- Sidebar Start -->
        <div class="sidebar pe-4 pb-3">
            <nav class="navbar bg-secondary navbar-dark">
                <a href="dashboard" class="navbar-brand mx-4 mb-3">
              <img class="logo" src="{{ asset('img/logo.png') }}" alt="Logo" style="width: 150px;margin-top: -50px;    
margin-bottom   : -67px; ">
                </a>
                <div class="d-flex align-items-center ms-4 mb-4">
                    <div class="position-relative">
                        <img class="rounded-circle" src="img/profile.png" alt="" style="width: 40px; height: 40px;">
                        <div class="bg-success rounded-circle border border-2 border-white position-absolute end-0 bottom-0 p-1"></div>
                    </div>
                    <div class="ms-3">
                        <h6 class="mb-0">Balkis Hmidi</h6>
                        <span>Admin</span>
                    </div>
                </div>
                <div class="navbar-nav w-100">
                    <a href="dashboard" class="nav-item nav-link"><i class="fa fa-tachometer-alt me-2"></i>Dashboard</a>
                    <div class="nav-item dropdown">
                         <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown"><i class="fa fa-user-edit me-2"></i>Utilisateurs</a>
                        <div class="dropdown-menu bg-transparent border-0">
                            <a href="#" class="dropdown-item">Clients</a>
                            <a href="#" class="dropdown-item">Conducteur</a>
                        </div>
                    </div>
                    <a href="#" class="nav-item nav-link"><i class="fa fa-th me-2"></i>Offres</a>
                    <a href="#" class="nav-item nav-link"><i class="fa fa-keyboard me-2"></i>Reservations</a>
                    <a  href="{{ path('app_commentaire') }}" class="nav-item nav-link active "><i class="fa fa-table me-2"></i>Commentaire</a>
                    <a href="{{ path('app_avis') }}" class="nav-item nav-link "><i class="fa fa-star me-2"></i>Avis</a>
                       <a href="/contratf/back"  class="nav-item nav-link" ><i class="far fa-file-alt me-2"></i>Contrats</a>
                    <a href="/aff" class="nav-item nav-link " ><i class="fa fa-keyboard me-2"></i>Réclamations</a>
                <a href="/message/aff" class="nav-item nav-link "><i class="fa fa-table me-2"></i>Messages</a>
                </div>
               
            </nav>
        </div>
        <!-- Sidebar End -->



{% endblock %}                    <a href="/aff" class="nav-item nav-link " ><i class="fa fa-keyboard me-2"></i>Réclamations</a>
                <a href="/message/aff" class="nav-item nav-link active"><i class="fa fa-table me-2"></i>Messages</a>
                </div>
               
            </nav>
        </div>
        <!-- Sidebar End -->



{% endblock %}
{% block body %}
    <!-- Form Start -->
            <div class="container-fluid pt-4 px-4">
                <div class="row g-4">
                    <div class="col-sm-12 col-xl-6">
                        <div class="bg-secondary rounded h-100 p-4">
                            <h6 class="mb-4">Envoyer message</h6>
                            {{ form_start(form , {'attr': {'novalidate':'novalidate'}} ) }}
                            <form>
                             <div class="row g-3">
                                <div class="col-md-6">
                                    <form class="forms-sample">
                      <div class="form-group">
                        {{ form_row(form.contenu, {'label':'Contenu' ,'attr':{'placeholder': 'keep it short and clear', 'class':'form-control'}}) }}
                        </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                        {{ form_row(form.date_message, {'label':'Selectionner la date' ,'attr':{'placeholder': 'date...', 'class':'form-control'}}) }}
                        </div>
                                </div>
                                

                         <div class="col-12">
                                    <div class="form-group">
                        {{ form_row(form.id_admin, {'label':'Admin' ,'attr':{'placeholder': 'admin...', 'class':'form-control'}}) }}
                        </div>
                        </div> 
                                <div class="col-12">
                                    <button class="btn btn-primary w-100 py-2" type="submit">Envoyer</button>
                                </div>
                            
                             {{form_end(form)}}
                        </form>
                        <a href="{{ path('app_message_index') }}">afficher les messages envoyés</a>
                        </div>
                    </div>
                     </div>
                    </div>

{% endblock %}

templates/message/show.html.twig
{% extends 'backbase.html.twig' %}

{% block title %}Message{% endblock %}
{% block header %}
       
        <!-- Sidebar Start -->
        <div class="sidebar pe-4 pb-3">
            <nav class="navbar bg-secondary navbar-dark">
                <a href="dashboard" class="navbar-brand mx-4 mb-3">
              <img class="logo" src="{{ asset('img/logo.png') }}" alt="Logo" style="width: 150px;margin-top: -50px;    
margin-bottom   : -67px; ">
                </a>
                <div class="d-flex align-items-center ms-4 mb-4">
                    <div class="position-relative">
                        <img class="rounded-circle" src="/img/profile.png" alt="" style="width: 40px; height: 40px;">
                        <div class="bg-success rounded-circle border border-2 border-white position-absolute end-0 bottom-0 p-1"></div>
                    </div>
                    <div class="ms-3">
                        <h6 class="mb-0">Balkis Hmidi</h6>
                        <span>Admin</span>
                    </div>
                </div>
                <div class="navbar-nav w-100">
                    <a href="dashboard" class="nav-item nav-link"><i class="fa fa-tachometer-alt me-2"></i>Dashboard</a>
                    <div class="nav-item dropdown">
                         <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown"><i class="fa fa-user-edit me-2"></i>Utilisateurs</a>
                        <div class="dropdown-menu bg-transparent border-0">
                            <a href="#" class="dropdown-item">Clients</a>
                            <a href="#" class="dropdown-item">Conducteur</a>
                        </div>
                    </div>
                    <a href="#" class="nav-item nav-link"><i class="fa fa-th me-2"></i>Offres</a>
                    <a href="#" class="nav-item nav-link"><i class="fa fa-keyboard me-2"></i>Reservations</a>
                    <a  href="{{ path('app_commentaire') }}" class="nav-item nav-link "><i class="fa fa-table me-2"></i>Commentaire</a>
                    <a href="{{ path('app_avis') }}" class="nav-item nav-link "><i class="fa fa-star me-2"></i>Avis</a>

{% block header %}
       
        <!-- Sidebar Start -->
        <div class="sidebar pe-4 pb-3">
            <nav class="navbar bg-secondary navbar-dark">
                <a href="dashboard" class="navbar-brand mx-4 mb-3">
              <img class="logo" src="{{ asset('img/logo.png') }}" alt="Logo" style="width: 150px;margin-top: -50px;    
margin-bottom   : -67px; ">
                </a>
                <div class="d-flex align-items-center ms-4 mb-4">
                    <div class="position-relative">
                        <img class="rounded-circle" src="img/profile.png" alt="" style="width: 40px; height: 40px;">
                        <div class="bg-success rounded-circle border border-2 border-white position-absolute end-0 bottom-0 p-1"></div>
                    </div>
                    <div class="ms-3">
                        <h6 class="mb-0">Balkis Hmidi</h6>
                        <span>Admin</span>
                    </div>
                </div>
                <div class="navbar-nav w-100">
                    <a href="dashboard" class="nav-item nav-link"><i class="fa fa-tachometer-alt me-2"></i>Dashboard</a>
                    <div class="nav-item dropdown">
                         <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown"><i class="fa fa-user-edit me-2"></i>Utilisateurs</a>
                        <div class="dropdown-menu bg-transparent border-0">
                            <a href="#" class="dropdown-item">Clients</a>
                            <a href="#" class="dropdown-item">Conducteur</a>
                        </div>
                    </div>
                    <a href="#" class="nav-item nav-link"><i class="fa fa-th me-2"></i>Offres</a>
                    <a href="#" class="nav-item nav-link"><i class="fa fa-keyboard me-2"></i>Reservations</a>
                    <a  href="{{ path('app_commentaire') }}" class="nav-item nav-link active "><i class="fa fa-table me-2"></i>Commentaire</a>
                    <a href="{{ path('app_avis') }}" class="nav-item nav-link "><i class="fa fa-star me-2"></i>Avis</a>
                       <a href="/contratf/back"  class="nav-item nav-link" ><i class="far fa-file-alt me-2"></i>Contrats</a>
                    <a href="/aff" class="nav-item nav-link " ><i class="fa fa-keyboard me-2"></i>Réclamations</a>
                <a href="/message/aff" class="nav-item nav-link "><i class="fa fa-table me-2"></i>Messages</a>
                </div>
               
            </nav>
        </div>
        <!-- Sidebar End -->



{% endblock %}                    <a href="/aff" class="nav-item nav-link " ><i class="fa fa-keyboard me-2"></i>Réclamations</a>
                <a href="/message/aff" class="nav-item nav-link active"><i class="fa fa-table me-2"></i>Messages</a>
                </div>
               
            </nav>
        </div>
        <!-- Sidebar End -->



{% endblock %}
{% block body %}
<style>
        h1 {
            color: black;
            font-size: 24px;
        }
    </style>
<div class="container" style="background-color: white; height: 800px;">

    <h1>Détail de message</h1>

    <table class="table table-bordered table-striped table-hover" style="width: 80%;">
    <tbody>
        <tr>
            <th style="color: #FF7F50;">Id de message envoyé</th>
            <td>{{ message.id }}</td>
        </tr>
        <tr>
            <th style="color: #FF7F50;">Contenu</th>
            <td>{{ message.contenu }}</td>
        </tr>
        <tr>
            <th style="color: #FF7F50;">Date_message</th>
            <td>{{ message.dateMessage ? message.dateMessage|date('Y-m-d') : '' }}</td>
        </tr>
    </tbody>
</table>
   {{ include('message/_delete_form.html.twig') }}
<a href="{{ path('app_message_edit', {'id': message.id}) }}" class="btn btn-danger btn-primary" style="margin-right: 10px;">Modifier</a>
<a href="{{ path('app_message_index') }}" class="btn btn-danger btn-secondary" style="margin-right: 10px;">Retour à la liste</a>
</div>
{% endblock %}

templates/message/showpourclient.html.twig
{% extends 'frontbase.html.twig' %}

{% block title %}Message{% endblock %}
{% block body %}
<div class="container-fluid d-flex align-items-center justify-content-center bg-white" style="height: 600px;">
  <div class="col-lg-6 wow fadeIn" data-wow-delay="0.5s">
    <div class="h-400 d-flex flex-column justify-content-center p-4" style="border-radius: 10px; background-color: #333333; width: 90%; margin: 0 auto; height: 500px;">

      <p class="d-inline-flex bg-white text-primary py-1 px-3 me-auto" style="border-radius: 5px;">Message reçu suite à votre réclamation</p>
      <div>
        <div class="d-flex justify-content-between border-bottom py-2">
          <h6 class="text-uppercase mb-0 text">Contenu</h6>
        </div>
        <div>
          <span class="text" style="color: #FF7F50;">{{ message.contenu }}</span>
        </div>
        <div class="pt-3" style="color: #FF7F50;">
  Cordialement, <br>
  L'équipe du service client.
</div>
        <div class="d-flex justify-content-between border-bottom py-2">
          <h6 class="text-uppercase mb-0 text">Date et heure</h6>
        </div>
        <div>
          <span class="text-uppercase" style="color: #FF7F50;">{{ message.dateMessage ? message.dateMessage|date('d/m/Y H:i') : '' }}</span>
        </div>
      </div>
    </div>
  </div>
</div>


{% endblock %}