src/Entity/Contrat.php
<?php

namespace App\Entity;

use App\Repository\ContratRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;


#[ORM\Entity(repositoryClass: ContratRepository::class)]
class Contrat
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(name: "id_contrat", type: "integer")]
    private ?int $id = null;

    #[ORM\Column]
    #[Assert\NotBlank(message:"Veuillez remplir ce champ")]
    private ?int $id_conducteur = null;

    #[ORM\Column]
    #[Assert\NotBlank(message:"Veuillez remplir ce champ")]
    private ?int $id_admin = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    #[Assert\GreaterThan("now", message: "La date de début doit être supérieure à la date d'aujourd'hui")]
    private ?\DateTimeInterface $date_debut = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    #[Assert\GreaterThan("now", message: "La date de début doit être supérieure à la date d'aujourd'hui")]
    private ?\DateTimeInterface $date_fin = null;

    #[ORM\Column]
    #[Assert\NotBlank(message:"Veuillez remplir ce champ ")]
    private ?float $prix = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message:"Veuillez remplir ce champ")]
    private ?string $statut = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message:"Veuillez remplir ce champ")]
    private ?string $qrCode = null;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdConducteur(): ?int
    {
        return $this->id_conducteur;
    }

    public function setIdConducteur(int $id_conducteur): self
    {
        $this->id_conducteur = $id_conducteur;

        return $this;
    }

    public function getIdAdmin(): ?int
    {
        return $this->id_admin;
    }

    public function setIdAdmin(int $id_admin): self
    {
        $this->id_admin = $id_admin;

        return $this;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->date_debut;
    }

    public function setDateDebut(\DateTimeInterface $date_debut): self
    {
        $this->date_debut = $date_debut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->date_fin;
    }

    public function setDateFin(\DateTimeInterface $date_fin): self
    {
        $this->date_fin = $date_fin;

        return $this;
    }

    public function getPrix(): ?float
    {
        return $this->prix;
    }

    public function setPrix(float $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    public function getStatut(): ?string
    {
        return $this->statut;
    }

    public function setStatut(string $statut): self
    {
        $this->statut = $statut;

        return $this;
    }

    public function getQrCode(): ?string
    {
        return $this->qrCode;
    }

    public function setQrCode(string $qrCode): self
    {
        $this->qrCode = $qrCode;

        return $this;
    }

    public function getIdAbonnement(): ?Abonnement
    {
        return $this->id_abonnement;
    }

    public function setIdAbonnement(?Abonnement $id_abonnement): self
    {
        $this->id_abonnement = $id_abonnement;

        return $this;
    }
}

src/Form/ContratType.php
<?php

namespace App\Form;

use App\Entity\Contrat;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;


class ContratType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $now = new \DateTime();
        $builder
            ->add('id_conducteur')
            ->add('id_admin')
            ->add('prix')
            ->add('date_debut', DateType::class, [
                'widget' => 'single_text',
                'data' => $now,
            ])
            ->add('date_fin', DateType::class, [
                // renders it as a single text box
                'widget' => 'single_text',
                'data' => $now,
            ])
            ->add('statut')
            ->add('qrCode')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Contrat::class,
        ]);
    }
}

src/Controller/ContratController.php
<?php

namespace App\Controller;

use Dompdf\Options;

use Dompdf\Dompdf;
use App\Entity\Abonnement;
use App\Entity\Contrat;
use App\Entity\Message;
use App\Form\AbonnementsType;
use App\Form\ContratType;
use App\Form\MessageType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;



#[Route('/contrat')]
class ContratController extends AbstractController
{
    #[Route('/', name: 'contrat_index', methods: ['GET'])]
    public function index(EntityManagerInterface $entityManager): Response
    {
        $ab = $entityManager
            ->getRepository(Contrat::class)
            ->findAll();


        return $this->render(
            'contrat/index.html.twig',
            [
                'ab' => $ab,
            ]
        );
    }

    #[Route('/add', name: 'contrat_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $message = new Contrat();
        $form = $this->createForm(ContratType::class, $message);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($message);
            $entityManager->flush();

            return $this->redirectToRoute('contrat_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('contrat/add.html.twig', [
            'message' => $message,
            'form' => $form,
        ]);
    }


    #[Route('/{id}/edit', name: 'contrat_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Contrat $ab, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ContratType::class, $ab);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('contrat_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('contrat/edit.html.twig', [
            'ab' => $ab,
            'form' => $form,
        ]);
    }

    /*#[Route('/{id}/delete', name: 'contrat_delete', methods: ['GET'])]
    public function delete(Request $request, Contrat $message, EntityManagerInterface $entityManager): Response
    {

        $entityManager->remove($message);
        $entityManager->flush();


        return $this->redirectToRoute('contrat_index', [], Response::HTTP_SEE_OTHER);
    }*/






    #[Route('/all', name: 'contrat_all', methods: ['GET', 'POST'])]

    public function indexFront(EntityManagerInterface $entityManager, /*Pdf $snappy*/): Response
    {
        $pdf = null;
        // $html = $this->renderView('contrat/pdf.html.twig', [
        //'data' => $pdf,
        //'snappy' => $snappy,
        //]);

        $ab = $entityManager
            ->getRepository(Contrat::class)
            ->findAll();
        //$pdf = $snappy->getOutputFromHtml($html);

        return $this->render(
            'contrat/indexfront.html.twig',
            [
                'ab' => $ab,
                //'pdf' => $pdf,
                //'snappy' => $snappy,
            ]
        );
    }


    #[Route('/create', name: 'contrat_create', methods: ['GET', 'POST'])]
    public function newFront(Request $request, EntityManagerInterface $entityManager): Response
    {
        $message = new Contrat();
        $form = $this->createForm(ContratType::class, $message);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($message);
            $entityManager->flush();

            return $this->redirectToRoute('contrat_all', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('contrat/addfront.html.twig', [
            'message' => $message,
            'form' => $form,
        ]);
    }


    #[Route('/{id}', name: 'contrat_update', methods: ['GET', 'POST'])]
    public function editfront(Request $request, Contrat $ab, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ContratType::class, $ab);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('contrat_all', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('contrat/editfront.html.twig', [
            'ab' => $ab,
            'form' => $form,
        ]);
    }

    #[Route('/delete/{id}', name: 'contrat_delete', methods: ['GET'])]
    public function deleteFront(Request $request, Contrat $message, EntityManagerInterface $entityManager): Response
    {

        $entityManager->remove($message);
        $entityManager->flush();


        return $this->redirectToRoute('contrat_index', [], Response::HTTP_SEE_OTHER);
    }

    // pdf method : 


    #[Route('/generate_pdf/{id}', name: 'generate_pdf', methods: ['GET', 'POST'])]
    public function generateContrat(Contrat $contrat)
    {

        $html = $this->renderView('contrat/pdf.html.twig', [
            'contrat' => $contrat
        ]);


        $options = new Options();
        $options->set('isRemoteEnabled', true);

        $dompdf = new Dompdf($options);
        $dompdf->loadHtml($html);
        $dompdf->setPaper('A4', 'portrait');
        $dompdf->render();

        $output = $dompdf->output();

        $response = new Response($output);
        $response->headers->set('Content-Type', 'application/pdf');
        $response->headers->set('Content-Disposition', 'inline; filename="contrat.pdf"');

        return $response;
    }

    //download pdf : 


    #[Route('/download_pdf/{id}', name: 'download_pdf', methods: ['GET', 'POST'])]

    public function downloadPdf(Contrat $contrat)
    {
        $options = new Options();
        $options->set('isRemoteEnabled', true);

        $dompdf = new Dompdf($options);

        // Render the HTML template for the PDF
        $html = $this->renderView('contrat/pdf.html.twig', [
            'contrat' => $contrat,
        ]);

        // Load the HTML into Dompdf
        $dompdf->loadHtml($html);

        // Set the paper size and orientation
        $dompdf->setPaper('A4', 'portrait');

        // Render the PDF
        $dompdf->render();

        // Get the PDF content as a string
        $pdfContent = $dompdf->output();

        // Create a new Symfony response with the PDF content
        $response = new Response($pdfContent);

        // Set the headers for a PDF file download
        $response->headers->set('Content-Type', 'application/pdf');
        $response->headers->set('Content-Disposition', 'attachment;filename="contrat_' . $contrat->getIdContrat() . '.pdf"');

        return $response;
    }
}

templates/contrat/add.html.twig
{% extends 'baseback.html.twig' %}
{% block body %}
<div class='d-none'>
  <div class="page-body">
          <div class="container-fluid">
            <div class="page-header">
            
            </div>
          </div>
          <!-- Container-fluid starts-->
          <div class="container-fluid">
            <div class="row">
                {{ form_start(form,{'attr':{'novalidate':'novalidate'}})}}

                    {{ form_widget(form) }}
                    <button class="btn">{{ button_label|default('Save') }}</button>
                {{ form_end(form) }}
            </div>
          </div>
          <!-- Container-fluid Ends-->
    </div>
    </div>
        
{% endblock %} 

templates/contrat/addfront.html.twig
{% extends 'basefront.html.twig' %}
{% block body %}
                {{ form_start(form,{'attr':{'novalidate':'novalidate'}})}}
                    {{ form_widget(form) }}
                    <button class="btn">{{ button_label|default('Save') }}</button>
                {{ form_end(form) }}
{% endblock %}

templates/contrat/edit.html.twig
{% extends 'baseback.html.twig' %}
{% block body %}
  <div class="page-body">
          <div class="container-fluid">
            <div class="page-header">
            
            </div>
          </div>
          <!-- Container-fluid starts-->
          <div class="container-fluid">
            <div class="row">
                {{ form_start(form,{'attr':{'novalidate':'novalidate'}})}}
                    {{ form_widget(form) }}
                    <button class="btn">{{ button_label|default('Save') }}</button>
                {{ form_end(form) }}
            </div>
          </div>
          <!-- Container-fluid Ends-->
    </div>
        
{% endblock %} 

templates/contrat/editfront.html.twig
{% extends 'basefront.html.twig' %}
{% block body %}

                {{ form_start(form,{'attr':{'novalidate':'novalidate'}})}}
                    {{ form_widget(form) }}
                    <button class="btn">{{ button_label|default('Save') }}</button>
                {{ form_end(form) }}
{% endblock %}

templates/contrat/index.html.twig
{% extends 'baseback.html.twig' %}
{% block body %}
            <div class="container-fluid pt-4 px-4">
                <div class="bg-secondary text-center rounded p-4">
                    <div class="d-flex align-items-center justify-content-between mb-4">
                        <h6 class="mb-0">Contrat</h6>
                        <a href="{{ path('contrat_new') }}"> <button class="btn btn-primary" type="button">Ajouter</button></a>
                    </div>
                    <div class="table-responsive">
                        <table class="table text-start align-middle table-bordered table-hover mb-0">
                            <thead>
                              <tr>
                                <th>id</th>
                                <th>date debut</th>
                                <th>date fin</th>
                                <th>prix</th>
                                <th>actions</th>
                              </tr>
                            </thead>
                            <tbody>
                              {% for a in ab %}
                                <tr>
                            <td>{{ a.idContrat }}</td>
                             <td>
                              
                              {{a.dateDebut ? a.dateDebut|date('Y-m-d') : '' }}
                            </td>
                             <td>
                              
                              {{a.dateFin ? a.dateFin|date('Y-m-d') : '' }}
                            </td>
                            <td>{{ a.prix }}</td>
                              
                            <td style='display:flex'>                    
                            <a href="{{ path('contrat_edit',{'id': a.idContrat}) }}"><button class="btn btn-primary" type="button">Modifier</button></a>
                            <a href="{{ path('contrat_delete',{'id': a.idContrat}) }}">
                            <button class="btn btn-danger" type="button">Supprimer</button>
                            </a>
                            </td>

                           
                          </tr>
                              {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
{% endblock %} 


templates/contrat/indexfront.html.twig
{% extends 'basefront.html.twig' %}
{% block body %}
 <!-- Working Hours Start -->
    <div class="container-xxl py-5">
        <div class="container">





                                    <a href="{{ path('contrat_create') }}"> <button class="btn btn-primary" type="button">Ajouter</button></a>

                              {% for a in ab %}
<a href="{{ path('generate_pdf',{'id': a.idContrat}) }}" class="btn btn-primary">Generate PDF</a>
   <a href="{{ path('download_pdf',{'id': a.idContrat}) }}" class="btn btn-primary">Download PDF</a>
                              {% endfor %}




            <div class="row g-0">
                <div class="col-lg-6 wow fadeIn" data-wow-delay="0.1s">
                    <div class="h-100">
                        <img class="img-fluid h-100" src="img/open.jpg" alt="">
                    </div>
                </div>
                <div class="col-lg-6 wow fadeIn" data-wow-delay="0.5s">
                    <div class="bg-secondary h-100 d-flex flex-column justify-content-center p-5">
                        <p class="d-inline-flex bg-dark text-primary py-1 px-4 me-auto">contrat </p>
                        <div>
                            {% for a in ab %}
                            <div class="d-flex justify-content-between border-bottom py-2">
                                <h6 class="text-uppercase mb-0">id de contrat </h6>
                                <span class="text-uppercase">{{ a.idContrat }}</span>
                            </div>
                            <div class="d-flex justify-content-between border-bottom py-2">
                                <h6 class="text-uppercase mb-0">date debut de contrat </h6>
                                <span class="text-uppercase">{{a.dateDebut ? a.dateDebut|date('Y-m-d') : '' }}</span>
                            </div>
                            <div class="d-flex justify-content-between border-bottom py-2">
                                <h6 class="text-uppercase mb-0">date fin de contrat </h6>
                                <span class="text-uppercase">{{a.dateFin ? a.dateFin|date('Y-m-d') : '' }}</span>
                            </div>
                            <div class="d-flex justify-content-between border-bottom py-2">
                                <h6 class="text-uppercase mb-0">prix</h6>
                                <span class="text-uppercase">{{ a.prix }}</span>
                            </div>
                            <div class="d-flex justify-content-between border-bottom py-2">
                                <h6 class="text-uppercase mb-0">actions </h6>
                                <span class="text-uppercase">***********************</span>
                            </div>

                            <div class="d-flex justify-content-between border-bottom py-2">


                            <a href="{{ path('contrat_update',{'id': a.idContrat}) }}">
                            <button class="btn btn-primary" type="button">Modifier</button></a>
                            <a href="{{ path('contrat_delete',{'id': a.idContrat}) }}">
                             <button class="btn btn-primary" type="button">Supprimer</button></a>
                             </div>
                                                         {% endfor %}
 
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Working Hours End -->












            <div class="d-none">
                <div class="bg-secondary text-center rounded p-4">
                    <div class="d-flex align-items-center justify-content-between mb-4">
                        <h6 class="mb-0">Contrat</h6>
                        <a href="{{ path('contrat_new') }}"> <button class="btn btn-primary" type="button">Ajouter</button></a>
                    </div>
                    <div class="table-responsive">
                        <table class="table text-start align-middle table-bordered table-hover mb-0">
                            <thead>
                              <tr>
                                <th>id</th>
                                <th>date debut</th>
                                <th>date fin</th>
                                <th>prix</th>
                                <th>actions</th>
                              </tr>
                            </thead>
                            <tbody>
                              {% for a in ab %}
                                <tr>
                            <td>{{ a.idContrat }}</td>
                             <td>
                              
                              {{a.dateDebut ? a.dateDebut|date('Y-m-d') : '' }}
                            </td>
                             <td>
                              
                              {{a.dateFin ? a.dateFin|date('Y-m-d') : '' }}
                            </td>
                            <td>{{ a.prix }}</td>
                              
                            <td style='display:flex'>
  <a href="{{ path('generate_pdf',{'id': a.idContrat}) }}" class="btn btn-primary">Generate PDF</a>
   <a href="{{ path('download_pdf',{'id': a.idContrat}) }}" class="btn btn-primary">Download PDF</a>

                            <a href="{{ path('contrat_edit',{'id': a.idContrat}) }}"><button class="btn btn-primary" type="button">Modifier</button></a>
                            <a href="{{ path('contrat_delete',{'id': a.idContrat}) }}">
                            <button class="btn btn-danger" type="button">Supprimer</button>
                            </a>
                            </td>

                           
                          </tr>
                              {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
{% endblock %} 


templates/contrat/pdf.html.twig

<!DOCTYPE html>
<html>
<head>
	<title style="color: red">Contrat {{ contrat.idContrat }}</title>
	<style>
		body {

			font-family: Garamond, serif;
			color: black;
			line-height: 1.5;
			margin: 0;
			border: 5px solid black;
			padding: 20px;
			text-align: justify;
		}
		p {
			margin-top: 20px;
			margin-bottom: 20px;
			font-size: 18px;
		}
		strong {
			font-weight: bold;
		}
	</style>
</head>
<body>
<img src="http://localhost:8000/logn1.png" alt="AutoXpress Logo " style="width: 100px; position: absolute; top: 0; right: 0;">
	<p >Nous sommes ravis que vous cher conducteur d'id numero  {{ contrat.idConducteur }} soyez disposé à signer ce contrat  num : {{ contrat.idContrat }}</p>
	<p>avec l admin d'ID : {{ contrat.idAdmin }}</p>
	<p>Nous sommes convaincus que vous serez satisfait de notre service et nous sommes impatients de vous fournir une expérience de Date Début: {{ contrat.dateDebut|date('d/m/Y') }}</p>
	<p><strong>jusqua Date Fin:</strong> {{ contrat.dateFin|date('d/m/Y') }}</p>
	<p><strong>avec le total Prix:</strong> {{ contrat.prix }}</p>
	<p><strong>le statut du contrat :</strong> {{ contrat.statut }}</p>
	<p><strong>QR Code:</strong> {{ contrat.qrCode }}</p>
	<p>Thank you for choosing our services.</p>
</body>
</html>